### ISSUE TITLE
Doesn't seem to work with 0.9.3

### ISSUE THREAD

**Issue by Blemming** [pauloamgomes/CockpitCMS-Autosave#1]
I put the folder in <cockpit-folder>/addons/
Renamed it Autosave

It crashed my cockpit.

Also in the readme the animated gif what version of cockpit is that, I really miss having column headers in the collection entries.

**Comment by pauloamgomes** [comment]
Hi @Blemming , I'm using latest version of Cockpit (next). Can you provide more details on the issue?

**Comment by Blemming** [comment]
sorry It was a permissions issue. About the entries, was the gif made on a previous cockpit version ? my collection entries looks like this :
![image](https://user-images.githubusercontent.com/12241815/68685575-53c5c980-0538-11ea-9730-79b874218845.png)

**Comment by pauloamgomes** [comment]
> sorry It was a permissions issue. About the entries, was the gif made on a previous cockpit version ? my collection entries looks like this :
> ![image](https://user-images.githubusercontent.com/12241815/68685575-53c5c980-0538-11ea-9730-79b874218845.png)

nops, not a previous version, in your case seems you have "Custom sortable entries" enabled in the collection definition, and they support only one column..
